project_id = "iydttpxppmjdtcrohlfj"

[functions.ai-suggestions]
verify_jwt = false

[functions.supervisor-ai-analysis]
verify_jwt = false

[functions.ai-document-search]
verify_jwt = false

[functions.crawl-urls]
verify_jwt = false
